<!DOCTYPE html>
<!-- sss -->
<html>
<title>index</title>

<body>
  <h1>JavaScript Demo</h1>
  <form></form>
  <div id="myDiv" data-appId="12345" data-myname="Nicholas"
    style="background-color: blue; width: 10px; height: 25px;margin-bottom: 20px"></div>
  https://stackblitz.com/
  https://codesandbox.io/
  <table>
    <tr>
      <th>日期</th>
      <th>章节</th>
    </tr>
    <tr>
      <td>
        0415
      </td>
      <td>
        第15章
      </td>
    </tr>
    <tr>
      <td>
        0416
      </td>
      <td>
        第16章
      </td>
    </tr>
    <tr>
      <td>
        0417
      </td>
      <td>
        第17章
      </td>
    </tr>
    <tr>
      <td>
        0418
      </td>
      <td>
        第18章
      </td>
    </tr>
    <tr>
      <td>
        0419
      </td>
      <td>
        第19章
      </td>
    </tr>
    <tr>
      <td>
        0420
      </td>
      <td>
        第20章
      </td>
    </tr>
    <tr>
      <td>
        0421
      </td>
      <td>
        第21章
      </td>
    </tr>
    <tr>
      <td>
        0422
      </td>
      <td>
        第22章
      </td>
    </tr>
    <tr>
      <td>
        0423
      </td>
      <td>
        第23章
      </td>
    </tr>
    <tr>
      <td>
        0424
      </td>
      <td>
        第24章
      </td>
    </tr>
    <tr>
      <td>
        0425
      </td>
      <td>
        第25章
      </td>
    </tr>
    <tr>
      <td>
        0426
      </td>
      <td>
        第26章
      </td>
    </tr>
    <tr>
      <td>
        0427
      </td>
      <td>
        第27章
      </td>
    </tr>
  </table>
</body>

<script>
async function foo() {
  console.log(1);
  return 3;
}
// 给返回的期约添加一个解决处理程序
foo().then(console.log);
console.log(2);
// 1
// 2
// 3
// 返回一个期约
async function qux() {
  return Promise.resolve("qux");
}
qux().then(console.log);
// qux

//在期约处理程序中一样，在异步函数中抛出错误会返回拒绝的期约：
async function foo1() {
  console.log(1);
  throw 3;
}
// 给返回的期约添加一个拒绝处理程序
foo1().catch(console.log);
console.log(2);
// 1
// 2
// 3

//拒绝期约的错误不会被异步函数捕获：
// async function foo2() {
//   console.log(1);
//   Promise.reject(3);
// }
// // Attach a rejected handler to the returned promise
// foo2().catch(console.log);
// console.log(2);
// // 1
// // 2
// // Uncaught (in promise): 3


// 等待一个原始值
async function foo11() {
  console.log(await "foo");
}
foo11();
// foo
// 等待一个没有实现 thenable 接口的对象
async function bar11() {
  console.log(await ["bar"]);
}
bar11();
// ['bar']
// 等待一个实现了 thenable 接口的非期约对象
async function baz11() {
  const thenable = {
    then(callback) {
      callback("baz");
    }
  };
  console.log(await thenable);
}
baz11();
// baz
// 等待一个期约
async function qux11() {
  console.log(await Promise.resolve("qux"));
}
qux11();
// qux
</script>
<style>
  #myDiv {
    border: 1px solid black;
    margin-top: 20px;
  }
</style>

</html>